# Generated by Django 3.0.8 on 2021-05-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210507_0534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='ip',
            field=models.CharField(max_length=50, verbose_name='Определятор'),
        ),
    ]
